# Generated by Django 4.1.7 on 2023-06-07 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 6, 7, 19, 3, 28, 546321))),
                ('devicetype', models.CharField(blank=True, max_length=255, null=True)),
                ('useragent', models.TextField(blank=True, default='', null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('is_geolocation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('continent_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('continent_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dma_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_in_european_union', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.pageview')),
            ],
        ),
    ]
